/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.2.0.134 */
/* Module Version: 1.2 */
/* Sat Jan 31 15:37:16 2015 */

/* parameterized module instance */
EFB_UFM __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .wbc_ufm_irq( ));
