/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.2.0.134 */
/* Module Version: 7.4 */
/* Sat Jan 31 15:35:34 2015 */

/* parameterized module instance */
USR_MEM __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
