/* Verilog module instantiation template generated by SCUBA Diamond_1.3_Production (92) */
/* Module Version: 7.1 */
/* Thu Mar 29 15:59:54 2012 */

/* parameterized module instance */
USR_MEM __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
